<img src="img/dsci511_header.png" width="600">

# Lecture 5: Introduction to NumPy

## Lecture learning objectives

- Use NumPy to create arrays with built-in functions inlcuding `np.array()`, `np.arange()`, `np.linspace()` and `np.full()`, `np.zeros()`, `np.ones()`
- Be able to access values from a NumPy array by numeric indexing and slicing and boolean indexing
- Perform mathematical operations on and with arrays.
- Explain what broadcasting is and how to use it.
- Reshape arrays by adding/removing/reshaping axes with `.reshape()`, `np.newaxis()`, `.ravel()`, `.flatten()`
- Understand how to use built-in NumPy functions like `np.sum()`, `np.mean()`, `np.log()` as stand alone functions or as methods of numpy arrays (when available)

## Introduction to NumPy

![](img/numpy.png)

- NumPy stands for "Numerical Python"

- Standard Python library used for working with arrays (i.e., vectors & matrices), linear algerba, and other numerical computations
- NumPy is written in C, making NumPy arrays faster and more memory efficient than Python lists, read more [here](https://www.labri.fr/perso/nrougier/from-python-to-numpy/))
- The [Numpy docs](https://numpy.org/doc/stable/index.html) have recently been updated and are excellent
- NumPy can be installed using `conda` (if not already):

```
conda install numpy
```

## NumPy arrays

### What are arrays?

- "n-dimensional" data structures

- Can contain all the basic dtypes, e.g., floats, integers, strings etc, but work best with numeric data
- Generally homogeneous, meaning that items in the array should be of the same type
- Compatible with NumPy's vast collection of built-in functions

![](img/numpy_arrays.png)

Source: [Medium.com](https://medium.com/hackernoon/10-machine-learning-data-science-and-deep-learning-courses-for-programmers-7edc56078cde)

- Usually we import numpy with the alias `np` (to avoid having to type out n-u-m-p-y every time we want to use it)

In [8]:
import numpy as np

- A numpy array is sort of like a list:

In [9]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [10]:
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

- But it has the type `ndarray`

In [11]:
type(my_array)

numpy.ndarray

- Unlike a list, arrays can only hold a single type (usually numbers):

In [12]:
my_list = [1, "hi"]
my_list

[1, 'hi']

In [13]:
my_array = np.array([1, "hi"])
my_array

array(['1', 'hi'], dtype='<U21')

- Above: it converted the integer `1` into the string `'1'`

### Creating arrays

- arrays are typically created using two main methods:
    1. From existing data (usually lists or tuples) using `np.array()`, like we saw above; or,
    2. Using built-in functions such as `np.arange()`, `np.linspace()`, `np.zeros()`, etc.

In [15]:
my_list = [1, 2, 3]
np.array(my_list)

array([1, 2, 3])

- Just like you can have "multi-dimensional lists" (by nesting lists in lists), You can have multi-dimensional arrays (indicated by double square brackets `[[ ]]`)

In [16]:
list_2d = [[1, 2], [3, 4], [5, 6]]
list_2d

[[1, 2], [3, 4], [5, 6]]

In [18]:
array_2d = np.array(list_2d)
array_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

> There is an important difference though: all sub-arrays in higher dimensions should have the same length, unlike nested lists.
For example, all sub-arrays of `array_2d` have 2 elements.

- You'll probably use the built-in numpy array creators quite often
- Here are some common ones (hint - don't forget to check the docstrings for help with these functions. if you're in Jupyter, remeber the `shift + tab` shortcut. In VSCode, hover over the function to see its docstrings):

In [19]:
np.arange(1, 5)  # from 1 inclusive to 5 exclusive

array([1, 2, 3, 4])

In [20]:
np.arange(0, 11, 2)  # step by 2 from 1 to 11

array([ 0,  2,  4,  6,  8, 10])

In [21]:
np.linspace(0, 10, 5)  # 5 equally spaced points between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
np.ones((2, 2))  # an array of ones with size 2 x 2

array([[1., 1.],
       [1., 1.]])

In [25]:
np.zeros((2, 3))  # an array of zeros with size 2 x 3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.full((3, 3), 3.14)  # an array of the number 3.14 with size 3 x 3

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [27]:
np.full((3, 3, 3), 3.14)  # an array of the number 3.14 with size 3 x 3 x 3

array([[[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]]])

In [28]:
np.random.rand(5, 5)  # random numbers uniformly distributed from 0 to 1 with size 5 x 2

array([[0.94671689, 0.75728724, 0.22556317, 0.94444026, 0.43242944],
       [0.80157677, 0.43055109, 0.19544969, 0.72042626, 0.09990809],
       [0.58056901, 0.36978974, 0.3297525 , 0.25331175, 0.46471   ],
       [0.18906922, 0.24796624, 0.12049759, 0.73718713, 0.68657856],
       [0.10086534, 0.6108868 , 0.03953648, 0.64344777, 0.54330625]])

- There are many useful attributes/methods that can be called off numpy arrays:

In [29]:
print(dir(np.ndarray))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '

In [30]:
x = np.random.rand(5, 2)
x

array([[0.18254139, 0.94184834],
       [0.85801473, 0.71431197],
       [0.20027693, 0.73958135],
       [0.77048161, 0.76815875],
       [0.96820828, 0.93797865]])

In [31]:
x.transpose()

array([[0.18254139, 0.85801473, 0.20027693, 0.77048161, 0.96820828],
       [0.94184834, 0.71431197, 0.73958135, 0.76815875, 0.93797865]])

In [32]:
x.T

array([[0.18254139, 0.85801473, 0.20027693, 0.77048161, 0.96820828],
       [0.94184834, 0.71431197, 0.73958135, 0.76815875, 0.93797865]])

In [33]:
x.mean()

0.7081402010711056

In [34]:
x.astype(int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

### Array shapes

- As you just saw above, arrays can be of any dimension, shape and size you desire
- In fact, there are three main array attributes you need to know to work out the characteristics of an array:
    - `.ndim`: the number of dimensions of an array
    - `.shape`: the number of elements in each dimension (like calling `len()` on each dimension)
    - `.size`: the total number of elements in an array (i.e., the product of `.shape`)

In [35]:
array_1d = np.ones(3)
print(f"Dimensions: {array_1d.ndim}")
print(f"     Shape: {array_1d.shape}")
print(f"      Size: {array_1d.size}")

Dimensions: 1
     Shape: (3,)
      Size: 3


- Let's turn that print action into a function and try out some other arrays

In [36]:
def print_array(x):
    print(f"Dimensions: {x.ndim}")
    print(f"     Shape: {x.shape}")
    print(f"      Size: {x.size}")
    print("")
    print(x, '\n')

In [37]:
array_2d = np.ones((3, 2))
print_array(array_2d)

Dimensions: 2
     Shape: (3, 2)
      Size: 6

[[1. 1.]
 [1. 1.]
 [1. 1.]] 



In [38]:
array_4d = np.ones((1, 2, 3, 4))
print_array(array_4d)

Dimensions: 4
     Shape: (1, 2, 3, 4)
      Size: 24

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]] 



- After 3 dimensions, printing arrays starts getting pretty messy
- Square brackets (`[ ]`) are used to denote dimensions

### 1-d arrays

Data of a 1D vector can have infinitely many representations in Numy. For example, it can be expressed as 1 row or 1 column of a 2D array. This can also be generalized to N-dimensional arrays:

In [44]:
x = np.ones(5)
print_array(x)

Dimensions: 1
     Shape: (5,)
      Size: 5

[1. 1. 1. 1. 1.] 



In [45]:
y = np.ones((1, 5))
print_array(y)

Dimensions: 2
     Shape: (1, 5)
      Size: 5

[[1. 1. 1. 1. 1.]] 



In [46]:
z = np.ones((5, 1))
print_array(z)

Dimensions: 2
     Shape: (5, 1)
      Size: 5

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]] 



- We can use `np.array_equal()` to determine if two arrays have the same shape and elements

In [47]:
np.array_equal(x, x)

True

In [48]:
np.array_equal(x, y)

False

In [49]:
np.array_equal(x, z)

False

In [50]:
np.array_equal(y, z)

False

- The shape of your 1-d arrays can actually have major implications on your mathematical operations!

In [51]:
print(f"x: {x}")
print(f"y: {y}")
print(f"z: {z}")

x: [1. 1. 1. 1. 1.]
y: [[1. 1. 1. 1. 1.]]
z: [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [52]:
x + y  # makes sense

array([[2., 2., 2., 2., 2.]])

In [53]:
y + z  # wait, what?

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

- What happened in the cell above is "broadcasting" and we'll discuss it below.

## Array operations and broadcasting

### Element-wise operations

- Element-wise operations refer to operations applied to each element of an array
- Or between the paired entries of two arrays

In [54]:
x = np.ones(4)
x

array([1., 1., 1., 1.])

In [55]:
y = x + 1
y

array([2., 2., 2., 2.])

In [56]:
x - y

array([-1., -1., -1., -1.])

In [57]:
x == y

array([False, False, False, False])

In [58]:
x * y

array([2., 2., 2., 2.])

In [59]:
x ** y

array([1., 1., 1., 1.])

In [60]:
x / y

array([0.5, 0.5, 0.5, 0.5])

In [61]:
np.array_equal(x, y)

False

### Broadcasting

- Arrays with different sizes cannot be directly used in arithmetic operations.


In [62]:
a = np.ones((2, 2))
b = np.ones((3, 3))
a + b

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

- `Broadcasting` describes how NumPy treats arrays with different shapes during arithmetic operations
- The idea is to wrangle data so that operations can occur element-wise

- Let's see an example, say I sell pies on my weekends
- I sell 3 types of pies at different prices, and I sold the following number of each pie last weekend
- I want to know how much money I made per pie type per day:

![](img/pies.png)

In [63]:
cost = np.array([20, 15, 25])
print("Pie cost ($):")
cost

Pie cost ($):


array([20, 15, 25])

In [64]:
sales = np.array([
    [2, 3, 1],
    [6, 3, 3],
    [5, 3, 5]]
)
print("\nPie sales (#):")
print(sales)


Pie sales (#):
[[2 3 1]
 [6 3 3]
 [5 3 5]]


- How can we multiply these two arrays together?
- We could use a loop:

![](img/pies_loop.png)

In [65]:
sales[:, 0] * cost

array([ 40,  90, 125])

In [66]:
sales.shape

(3, 3)

In [67]:
total = np.zeros((3, 3))  # initialize an array of 0's

for col in range(sales.shape[1]):
    total[:, col] = sales[:, col] * cost
    
total

array([[ 40.,  60.,  20.],
       [ 90.,  45.,  45.],
       [125.,  75., 125.]])

- OR, we could make them the same size, and multiply corresponding elements "elementwise"

![](img/pies_broadcast.png)

In [68]:
cost = cost.reshape(3, 1).repeat(3, axis=1)
cost

array([[20, 20, 20],
       [15, 15, 15],
       [25, 25, 25]])

In [69]:
cost * sales

array([[ 40,  60,  20],
       [ 90,  45,  45],
       [125,  75, 125]])

- Congratulations! You just broadcasted!
- Numpy effectively does the `np.repeat()` for you under the hood

In [70]:
cost = np.array([20, 15, 25]).reshape(3, 1)
print(f" cost shape: {cost.shape}")
sales = np.array([
    [2, 3, 1],
    [6, 3, 3],
    [5, 3, 5]]
)
print(f"sales shape: {sales.shape}")

 cost shape: (3, 1)
sales shape: (3, 3)


In [71]:
sales * cost

array([[ 40,  60,  20],
       [ 90,  45,  45],
       [125,  75, 125]])

- In NumPy the smaller array is “broadcast” across the larger array so that they have compatible shapes

![](img/broadcasting.png)

Source: [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/) by Jake VanderPlas (2016)

- Why should you care about broadcasting?
- Well, it's cleaner and faster than looping
- It also affects the array shapes resulting from arithmetic operations
- Below, we can time how long it takes to loop vs broadcast:

In [74]:
cost = np.array([20, 15, 25]).reshape(3, 1)
sales = np.array([[2, 3, 1],
                  [6, 3, 3],
                  [5, 3, 5]])
total = np.zeros((3, 3))

time_loop = %timeit -q -o -r 3 for col in range(sales.shape[1]): total[:, col] = sales[:, col] * np.squeeze(cost)
time_vec = %timeit -q -o -r 3 cost * sales
print(f"Broadcasting is {time_loop.average / time_vec.average:.2f}x faster than looping here.")

Broadcasting is 4.91x faster than looping here.


- Arrays can only be broadcast together if they are compatible in all dimensions.
- Of course, not all arrays are compatible!
- Dimensions are compatible if:
    - **they are equal**, or
    - **one of them is 1**.
- NumPy checks for dimensional compatibility by starting from the right-most dimension.
- Consider these two examples from NumPy's documentation:

```
Broadcastable:
A      (3d array): 256 x 256 x 3
B      (1d array):             3
Result (3d array): 256 x 256 x 3

A      (4d array): 8 x 1 x 6 x 1
B      (3d array):     7 x 1 x 5
Result (4d array): 8 x 7 x 6 x 5
```

- Use the code below to test out array compatibility:

In [75]:
a = np.ones((3, 2))
b = np.ones((3, 2, 1))
print("The shape of a is:" + f"{a.shape}".rjust(10))
print("The shape of b is:" + f"{b.shape}".rjust(10))
print("")
try:
    print(f"The shape of a + b is: {(a + b).shape}")
except:
    print(f"ERROR: arrays are NOT broadcast compatible!")

The shape of a is:    (3, 2)
The shape of b is: (3, 2, 1)

ERROR: arrays are NOT broadcast compatible!


### Reshaping arrays

- There are 3 key reshaping methods I want you to know about for reshaping numpy arrays:
    - `.rehshape()`
    - `np.newaxis`
    - `.ravel()`/`.flatten()`

In [124]:
x = np.random.randint(10, size=(4, 3))
x

array([[6, 2, 8],
       [5, 2, 4],
       [5, 3, 8],
       [5, 1, 3]])

- You'll reshape arrays farily often and the `.reshape()` method is pretty intuitive:

In [78]:
x.reshape(6, 2)

array([[9, 3],
       [4, 4],
       [0, 5],
       [5, 8],
       [5, 0],
       [7, 1]])

In [79]:
x.reshape(6, -1)  # using -1 will calculate the dimension for you (if possible)

array([[9, 3],
       [4, 4],
       [0, 5],
       [5, 8],
       [5, 0],
       [7, 1]])

- Note that the default order for reshaping is row-major. You can set `order=F` to get a column-major reshaping. The following image (source: [Wikipedia](https://en.wikipedia.org/wiki/Row-_and_column-major_order)) illustrates this point:

![](img/row_column_major.png)

In [85]:
x

array([[9, 3, 4],
       [4, 0, 5],
       [5, 8, 5],
       [0, 7, 1]])

In [83]:
x.reshape(2, -1)

array([[9, 3, 4, 4, 0, 5],
       [5, 8, 5, 0, 7, 1]])

In [86]:
x.reshape(2, -1, order='F')

array([[9, 5, 3, 8, 4, 5],
       [4, 0, 0, 7, 5, 1]])

**Remember that:** You always both read AND write in a row-major or column-major way. For example, if you read in the row-major way, you'll also write in the row-major way.

> If you're interested, you can learn more about how arrays are represented in the memory and details of reshaping in the [appendix](#Appendix-(OPTIONAL)).

The way data is stored in the memory (row-major or column-major) can sometimes have significant performance implications. Consider the following examples:

In [182]:
a = np.random.rand(5000, 5000)
%timeit a[0, :].sum()

1.7 µs ± 5.37 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [183]:
a = np.random.rand(5000, 5000)
%timeit a[:, 0].sum()

13.9 µs ± 128 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In the latter case, we just changed the code to sum over a column, instead of over a row.

The reason for this difference is that when NumPy does operations on the columns of a row-major array, the CPU of your computer _pre-loads_ neighboring chunks of memory into its cache (a smaller, faster memory very close to the CPU core) and therefore processes the data faster. However, data in rows are not "contiguous" for a row-major array, which means that the CPU has to make much more frequent memory accesses and this considerably slows down the computations.

- Sometimes you'll want to add dimensions to an array for broadcasting purposes
- We can do that with `np.newaxis`
- Also note that `None` is an alias for `np.newaxis`

In [87]:
a = np.ones(3)
print_array(a)

Dimensions: 1
     Shape: (3,)
      Size: 3

[1. 1. 1.] 



In [88]:
b = np.ones((3, 2))
print_array(b)

Dimensions: 2
     Shape: (3, 2)
      Size: 6

[[1. 1.]
 [1. 1.]
 [1. 1.]] 



- If I want to add these two arrays I won't be able to because their dimensions are not compatible:

In [89]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

- We can add a dimension to `a` to make the arrays compatible:

In [90]:
print_array(a[:, np.newaxis])  # same as a[:, None]

Dimensions: 2
     Shape: (3, 1)
      Size: 3

[[1.]
 [1.]
 [1.]] 



In [91]:
a[:, np.newaxis] + b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

- We also can do the same using `.reshape()`:

In [92]:
a.reshape(-1, 1) + b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

- Finally, sometimes you'll want to "flatten" arrays to a single dimension using `.ravel()` or `.flatten()`
- `.flatten()` always returns a copy [[docs](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html#)], but `.ravel()` returns a copy only if needed [[docs](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html)]. Otherwise, it will return a view.

In [93]:
x

array([[9, 3, 4],
       [4, 0, 5],
       [5, 8, 5],
       [0, 7, 1]])

Outputs of these two methods look the same:

In [94]:
print_array(x.flatten())

Dimensions: 1
     Shape: (12,)
      Size: 12

[9 3 4 4 0 5 5 8 5 0 7 1] 



In [95]:
print_array(x.ravel())

Dimensions: 1
     Shape: (12,)
      Size: 12

[9 3 4 4 0 5 5 8 5 0 7 1] 



But here you can see that `.ravel()` might return a view, which means that modifying the "ravel-ed" version will also modify the original array:

In [125]:
y = x.flatten()
y[0] = 1000
x  # x stays intact

array([[6, 2, 8],
       [5, 2, 4],
       [5, 3, 8],
       [5, 1, 3]])

In [122]:
y = x.ravel()
y[0] = 1000
x  # x will change as well!

array([[1000,    3,    4],
       [   4,    0,    5],
       [   5,    8,    5],
       [   0,    7,    1]])

## Indexing and slicing

- Concepts of indexing should be pretty familiar by now
- Indexing arrays is similar to indexing lists but there are just more dimensions

### Numeric indexing

In [142]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
x[3]

3

In [144]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
x[:4]

array([0, 1, 2, 3])

In [146]:
x[2:5]

array([2, 3, 4])

In [147]:
x[2:3]

array([2])

In [148]:
x[-1]

9

In [149]:
x[-2]

8

In [150]:
x[5:0:-1]

array([5, 4, 3, 2, 1])

In [151]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

For 2D arrays:

In [152]:
x = np.random.randint(10, size=(4, 6))
x

array([[7, 6, 5, 2, 2, 6],
       [9, 5, 5, 8, 9, 7],
       [1, 7, 5, 1, 8, 6],
       [7, 1, 2, 2, 6, 1]])

In [153]:
x[3, 4]  # do this

6

In [154]:
x[3][4]  # C++ style. Not recommended for NumPy

6

In [155]:
x[3]

array([7, 1, 2, 2, 6, 1])

In [156]:
len(x)  # generally, just confusing

4

In [157]:
x.shape

(4, 6)

In [158]:
x[:, 2]  # column number 2

array([5, 5, 5, 2])

In [159]:
x[2:, :3]

array([[1, 7, 5],
       [7, 1, 2]])

In [160]:
x.T

array([[7, 9, 1, 7],
       [6, 5, 7, 1],
       [5, 5, 5, 2],
       [2, 8, 1, 2],
       [2, 9, 8, 6],
       [6, 7, 6, 1]])

In [161]:
x

array([[7, 6, 5, 2, 2, 6],
       [9, 5, 5, 8, 9, 7],
       [1, 7, 5, 1, 8, 6],
       [7, 1, 2, 2, 6, 1]])

In [162]:
x[1, 1] = 555555
x

array([[     7,      6,      5,      2,      2,      6],
       [     9, 555555,      5,      8,      9,      7],
       [     1,      7,      5,      1,      8,      6],
       [     7,      1,      2,      2,      6,      1]])

In [163]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [164]:
z[0] = 5
z

array([5., 0., 0., 0., 0.])

### Boolean indexing

In [165]:
x = np.random.rand(10)
x

array([0.56064701, 0.26621099, 0.96405696, 0.38116428, 0.750151  ,
       0.78806717, 0.17594937, 0.4513151 , 0.11085997, 0.58619287])

In [166]:
x + 1

array([1.56064701, 1.26621099, 1.96405696, 1.38116428, 1.750151  ,
       1.78806717, 1.17594937, 1.4513151 , 1.11085997, 1.58619287])

In [167]:
x_thresh = x > 0.5
x_thresh

array([ True, False,  True, False,  True,  True, False, False, False,
        True])

In [168]:
x[x_thresh] = 1  # set all elements  > 0.5 to be equal to 0.5
x

array([1.        , 0.26621099, 1.        , 0.38116428, 1.        ,
       1.        , 0.17594937, 0.4513151 , 0.11085997, 1.        ])

In [169]:
x = np.random.rand(10)
x

array([0.89612743, 0.09080129, 0.50654345, 0.24295301, 0.76580837,
       0.98933606, 0.27837662, 0.68961772, 0.13100269, 0.63462897])

In [170]:
x[x > 0.5] = 1
x

array([1.        , 0.09080129, 1.        , 0.24295301, 1.        ,
       1.        , 0.27837662, 1.        , 0.13100269, 1.        ])

## More useful NumPy functions

- NumPy has many built-in functions for mathematical operations
- Almost any numerical operation you want to do (and if it can't, `SciPy` probably will be able to)
- We don't have time to look at all the possible operations
- But consider working out the hypotenuse of a triangle that with sides 3 and 4:

![](img/triangle.png)

In [ ]:
sides = np.array([3, 4])

- There are several ways we could solve this problem
- We could directly use Pythagoras's Theorem

$$c = \sqrt{a^2+b^2}$$

In [ ]:
np.sqrt(np.sum([np.power(sides[0], 2), np.power(sides[1], 2)]))

- We can leverage the fact that we're dealing with a numpy array and apply a "vectorized" operation (more on that in a second) to the whole vector at one time:

In [ ]:
(sides ** 2).sum() ** 0.5

- Or we can simply use a numpy built-in function (if it exists)

In [ ]:
np.linalg.norm(sides)  # you'll learn more about norms in 573

In [ ]:
np.hypot(*sides)

### Vectorization

- Broadly speaking, "vectorization" in NumPy refers to the use of array-level operations done by optimized C code.

- Instead of using **slow** Python loops to go through every element, super-**fast** C loops are used under the hood by NumPy to perform array operations.

- Because NumPy arrays are homogeneous (contain the same dtype), we don't need to check that we can perform an operation on elements of a sequence before we do the operation which results in a huge speed-up.

- Read more about vectorization [here](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/VectorizedOperations.html)
- All you need to know is that most operations in NumPy are vectorized, so just try to do things at an "array-level" rather than an "element-level", e.g.:

In [196]:
# DO NOT DO THIS
array = np.array(range(5))
for i, element in enumerate(array):
    array[i] = element ** 2
array

array([ 0,  1,  4,  9, 16])

In [197]:
# DO THIS
array = np.array(range(5))
array += 2
array

array([2, 3, 4, 5, 6])

- Let's do a quick timing experiment:

In [200]:
# loop method
array = np.array(range(1000))
time_loop = %timeit -q -o -r 3 for i, element in enumerate(array): array[i] = element ** 2
# vectorized method
array = np.array(range(1000))
time_vec = %timeit -q -o -r 3 array ** 2
print(f"Vectorized operation is {time_loop.average / time_vec.average:.2f}x faster than looping here.")

Vectorized operation is 170.86x faster than looping here.


## Appendix (OPTIONAL)

In this appendix, I'll show more about how NumPy manages and stores arrays in memory. **This is completely optional material**. I'll stress that a thorough understanding of the NumPy internals like how memory is handled and accessed is really more for developers working on super-optimized algorithms or for those interested in these kinds of things. The data scientist who does not care about these implementation details can just continue to visualize and use arrays as N-dimensional data structures—after all, the point of NumPy is to abstract away the technical implementation details so such users can focus on writing code and wrangling data.

This appendix draws on excellent material presented in:
- [The NumPy documentation](https://numpy.org/doc/stable/reference/internals.html)
- [Guide to NumPy](https://web.mit.edu/dvp/Public/numpybook.pdf) by Travis Oliphant, 2006

### Array data type

All ndarrays are homogeneous, meaning that every element has the exact same data-type (e.g., integer, float, string, etc) which takes up the exact same amount of memory.

For example, consider the following 1d-array which is full of 8-bit integers (`int8`):

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6], dtype='int8')
a

One byte is equal to eight bits ([refresh yourself on bits and bytes here](https://web.stanford.edu/class/cs101/bits-bytes.html)), so for this array of `int8` data-types, we would expect each element to take up one byte. We can confirm using:

In [ ]:
a.itemsize

> An aside on the difference between e.g., `int8`, `int16`, `int32`. The number here refers to the number of bits used to represent each integer. For example, `int8` is an integer represented with one byte (one byte = 8 bits). Recall that bits (i.e., 0s and 1s) are the basic units of information used by computers. So the maximum *unsigned* number that can be held with an `int8` datatype is: $2^8=256$. If we wish to have negative numbers, we need to use one of those bits to represent the sign, and we are left with $2^7$ bits to make numbers with, and so the signed range of `int8` is -128 to +127. Likewise, `int16` has an unsigned range of 0 to 65,535 ($2^{16}$), or a signed range of -32,768 to +32,767, etc. It's interesting to watch what happens if you try to use a dtype that does not support the number you wish to store:

In [ ]:
np.array([126, 127, 128, 129, 130, 131, 132], dtype='int8')

>Above, notice how when we exceeded the integer 127 (the max of the `int8` signed range), NumPy automatically represents this number by counting up from the minimum of the signed range (-128). Of course, this wouldn't be a problem if we used `int16`:

In [ ]:
np.array([126, 127, 128, 129, 130, 131, 132], dtype='int16')

Finally I'll say that technically it is possible to have mixed data-types in an array (i.e., a heterogenous array), but in this case, the array still "sees" each element as the same thing: a reference to some Python object, and the dtype would be "object".

In [ ]:
a = np.array([['a', 'b', 'c'], 1, 3.14159], dtype='object')
a

Above is an ndarrays of objects, each one being a reference to some other Python object with its own data-type:

In [ ]:
list(map(type, a))

Using arrays like this negates much of the optimized functionality that comes with them, and I can't recall a time when I've used a "heterogenous array". For mixed data-types, I would typically use other structures like lists or dictionaries.

### Memory layout & strides

Now that we've covered the basic concepts of ndarrays, we can talk more about how arrays are represented in memory. An ndarray is stored as a single “chunk” of memory starting at some location. It's helpful to think of it as a one-dimensional sequence in memory but with "fancy indexing" that can help map an N-dimensional index (for ndarrays) into that one-dimensional representation.

Consider "**Panel a**" in the below conceptual figure from the paper [Array programming with NumPy](https://www.nature.com/articles/s41586-020-2649-2), showing how a 2d-array of data-type `int64` (8 bytes) is represented in memory as a single chunk:

![](img/numpy_paper.png)

That word **strides** (stride means "one long step") is the number of bytes you need to step in each dimension when traversing the array. As you can see in the example, the **stride** information is particularly important for mapping the chunk of memory back to a n-dimensional array structure. So in the above case, the strides is `(24, 8)` meaning 24 bytes (three 8-byte `int64` elements) and 8 bytes (one 8-byte `int64` element), meaning that every 3 elements we increment our first dimension (i.e., move to the next row) and every 1 element we increment our second dimension (i.e., move to the next column).

Let's go through another example:

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype='int16')
a

Here we have an ndarray of shape `(3, 2)` and with a dtype of `int16` (2 bytes per element in the array). We would expect the stride to be `(4, 2)` (every 4 bytes, which is 2 elements here for `int16`, we begin a new row, and every 2 bytes, which is 1 element here, we begin a new column). We can confirm with:

In [ ]:
a.strides

Neat! We could actually change how our ndarray maps from the memory block back to the ndarray by changing the stride information:

In [ ]:
a.strides = (2, 4)
a

To further drive the point home, what do you expect the strides to be of a 1D array? In that case, there is only one dimension to traverse, so we'd expect the strides to just be the number of bytes of 1 element, `(2,)` (i.e., every 2 bytes, which is one `int16` element). Let's confirm:

In [ ]:
a = a.flatten()
a

In [ ]:
a.strides

Finally, let's look at the strides of the following 3D array of size `(3,3,2)` but with the data-type `int8` (so that 1 byte = 1 element which makes interpreting strides a little easier). Visualizing 3D arrays starts to get a bit tricker, but I think of them as matrices stacked together like slices in a loaf of bread, or multiple chessboards stacked on top of each other.

In [ ]:
a = np.arange(18, dtype='int8').reshape(3, 3, 2)
a

In [ ]:
a.strides

Now things are getting a little more confusing! The above is saying that every 6 elements we increment a "depth dimension", every 2 elements we increment a "row dimension" and every 1 element we increment a "column dimension". Using our chessboard analogy, every 6 elements in memory we move to the next chessboard in the stack, every 2 elements we move down one row of a chessboard and every element we move across 1 column of our chessboard. I'll talk more about this 3D example in the next section.

### Why do we care?

#### Reshaping

One sometimes-confusing topic in NumPy is understanding how ndarrays are reshaped. But now that you understand how ndarrays are represented in memory, you can better understand how reshaping works in NumPy too! Basically, you can think of reshaping as viewing that "chunk" of memory in a different way (reading it into a different shape but preserving the ordering of the data in memory). Consider the same 2D array we just saw earlier, but with the data-type `int8` (so that 1 byte = 1 element which makes interpreting strides a little easier):

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype='int8')
a

In [ ]:
a.strides

When we reshape the array, think of it as flattening the array out:

In [ ]:
a.flatten()

And then reading that data back into a different shape with different strides. Below I'll change the shape to be `(2, 3)`, which means that we'll need strides of `(3, 1)` (every 3 elements, increment a row, every 1 element, increment a column in the array).

In [ ]:
a.shape = (2, 3)
a.strides = (3, 1)
a

> Above, I didn't need to do `a.strides`. When I changed the shape to `(2, 3)`, NumPy already took care of changing the strides for me, but I'm showing it for demonstration purposes.

The same logic applies to reshaping ndarrays of more than 2 dimensions. For example:

In [ ]:
a = np.arange(18, dtype='int8')
a

In [ ]:
a = a.reshape(3, 3, 2)
a

In [ ]:
a.strides

In the above example, we have three 2D matrix stacked together (I'll call them "slices"). We use the first 6 elements of our flattened array to fill in the first "slice", and within that 2D slice, those elements are arranged in rows and columns dictated by the strides (i.e., every 2 elements increment a row and every 1 element increment a column). Once we've used the first 6 elements, we traverse a dimensional "slice" and use the next 6 element to fill that 2D slice. We then repeat that one more time for the last "slice".

You might be wondering two things at this point:

1. Why is our array above composed of 3 slices of 3x2 matrices and not 2 slices of 3x3 matrices? 
2. How did NumPy decide to fill each 2D matrix slice with elements first, why not fill along the "depth" dimension first?

These questions are related and actually much deeper than you might expect. They are explained in detail in the [NumPy documentation](https://numpy.org/doc/stable/reference/internals.html#multidimensional-array-indexing-order-issues) and in section *2.3 Memory Layout of ndarray* in the book [Guide to NumPy](https://web.mit.edu/dvp/Public/numpybook.pdf) by Travis Oliphant, but they are to do with the fundamental implementation of how NumPy reads data from memory.

Briefly, NumPy uses "row-major" indexing when reading data from memory which basically means that "grouping" starts from the left most index. So for a 2D array, the order is `(row, column)`, for a 3D array the order is `(depth, row, column)`, for a 4D array it is `(4th dimension, depth, row, column)`, etc. The way I think about this is that the ndarray is a container, in the 3D case I think of a cube made up of stacked matrices. I can enter this for container ("dimension") and view a matrix. The next container is a "row" of values which comprises one smaller container for each "column". There are two overarching styles that dictate the way data is read in from memory, they are the "C style" and "Fortran style". NumPy uses the "C style" by default which is what we saw above:

In [ ]:
a = np.arange(18, dtype='int8').reshape(3, 3, 2, order="C")
a

But there is also the "Fortran style", which you can see in the example below and can specify using the `order` argument, which appears to fill the "depth" dimension first:

In [ ]:
a = np.arange(18, dtype='int8').reshape(3, 3, 2, order="F")
a

These implementation details are not really necessary to know unless your developing algorithms or packages like NumPy that are directly interfacing with a computer's memory.

#### Super-speed code

Knowing about how ndarrays are stored in memory and what strides are can help us leverage some pretty nifty tricks to speed up our NumPy code. Consider performing convolution on a 2D image by passinga filter window of "weights" over the image pixels:

![](img/convolution.gif)

[(source: Wikipedia)](https://de.wikipedia.org/wiki/Convolutional_Neural_Network)

There are plenty of ways to solve this problem. The goal is really to apply our filter to windowed segments of our array. One way we can "view" our array as windows is using strides and the `numpy.lib.stride_tricks` module. Here's a 400 x 400 pixel image of the UBC sign:

In [ ]:
import time
import matplotlib.pyplot as plt
from numpy.lib.stride_tricks import as_strided
%config InlineBackend.figure_formats = ['svg']
plt.rcParams.update({'font.size': 14, 'figure.figsize': (6, 4), 'axes.grid': False})

In [ ]:
image = plt.imread('img/ubc.jpeg')[:, :, 0]
plt.imshow(image, cmap='gray')

Before applying the filter, let's take a look at the datatype and the number of strides for the `image` (which is saved as a NumPy array):

In [ ]:
image.dtype

In [ ]:
image.strides

The unsigned integer datatype `unint8` should take up 1 byte per element. So you might probably expect to see `(400, 1)` for strides. What's happened? Why `(1200, 3)`?

The reason is when the image file is read using `plt.imread('img/ubc.jpeg')` it is originally strided as `(1200, 3, 1)` before slicing:

In [ ]:
plt.imread('img/ubc.jpeg').strides

This is because the image is 400x400, but since it is an RGB image, the array needs to store 400x400 values for each of the RGB colors, making the shape of the array `(400, 400, 3)`.

When we slice the array to pick one of the channels though (using `[:, :, 0]`), the original array in the memory does not change. This is why NumPy still has to traverse 1200 elements (instead of 400) to reach the next row and 3 elements to get to the next column. That's why we get `(1200, 3)` when we run `image.strides`!

The image below from [here](https://eli.thegreenplace.net/2015/memory-layout-of-multi-dimensional-arrays) nicely demonstrates how three dimensional arrays are stored in the memory in a **row-major** manner:

![](img/row-major-3D.png)

Phew! Back to our filtering task:

This is the filter I want to apply to the image:

In [ ]:
f = np.array([[-2, -1, 0],
              [-1, 1, 1],
              [0, 1, 2]])

Now I'll use strides to view the image as 3 x 3 windows, so I can just apply the filter to every single window. Basically the goal here is to view our array as a series of 3x3 windows. So think of this as, for each pixel in our image, we want to view a 3x3 window around that pixel. We have 400x400 pixels, and if we have a 3x3 window for each pixel, we will have a 4D view of our array with shape `(400, 400, 3, 3)`. In this case, we can't have a 3x3 window at the edges of the image, so I'm just going to cut those off with our final shape being `(398, 398, 3, 3)` (but you could just pad the image with 0's to apply the filter at the edges if you wanted to). Once we have our 4D view, I can just apply the filter to each of those 3x3 windows and sum the numbers in each window. No `for` loops or complex functions needed!

In [ ]:
start = time.time()    # start time
size = f.shape[0]      # filter size
win_img = as_strided(  # Now use as_strided to get a windowed view of the array
    image,             # image to view as windows
    shape=(image.shape[0] - size + 1, image.shape[1] - size + 1, size, size),  # the shape of the new view (398, 398, 3, 3), the edge pixels are cut-off, but we could always pad if we wanted to here
    strides=image.strides * 2,  # this just duplicates the strides as we are now working in 4 dimensions, strides will be (1200, 3, 1200, 3)
)
filtered_image = (win_img * f).sum(axis=(2, 3))  # apply filter to each window (the 3rd and 4th dimensions of win_img)
plt.imshow(filtered_image, cmap="gray")
print(f"Wall time taken for convolution: {time.time()-start:.4f}s")

Even though `as_strided()` creates a new array, it uses the same data in memory as the original array. **The only thing that changes is the metadata, which changes how the array is viewed.**

If that example was a little too much for you right now, Jessica Yung provides a nice simple example of using arrays and strides in the blog post [What makes Numpy Arrays Fast: Memory and Strides](https://www.jessicayung.com/numpy-arrays-memory-and-strides/).